spring.application.name=Earthquake_Assignement
spring.datasource.url=jdbc:postgresql://localhost:5432/earthquake_db
spring.datasource.username=${DB_USERNAME:earthquake_user}
spring.datasource.password=${DB_PASSWORD:earthquake_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
